create schema if not exists data;

drop table if exists data.category cascade;
create table data.category (
    category_id int not null primary key generated by default as identity,
    --  generated by default as identity - jeżeli nie zostanie wpisany category_id program sam tp zrobi
    name text not null,
    image_src text not null
);


drop table if exists data.product cascade;
create table data.product (
    product_id int not null primary key generated by default as identity,
    name text not null,
    image_src text not null,
    price numeric(5, 2) not null,
    description text
);

drop table if exists data.subcategory cascade;
create table data.subcategory (
    subcategory_id int not null primary key generated by default as identity,
    category_id int not null references data.category(category_id),
    name text not null,
    description text null

);

drop table if exists data.subcategory_to_product cascade;
create table data.subcategory_to_product (
    subcategory_id int references data.subcategory (subcategory_id),
    product_id int references data.product (product_id),
    primary key (subcategory_id, product_id)
);

